### PR TITLE
Hyderabad Landuse Data

### PR DESCRIPTION
**Pull request by sandeepgadhwal**

### CODE REVIEW

**Comment by sandeepgadhwal** [comment]
What is the progress on this request

**Comment by devdattaT** [comment]
I'll have a look at it by weekned.
I'm actually wondering if we should put in the Landuse data in this repo, or we should keep it separate since this one focuses on Municipal data.

@thejeshgn What do you suggest?

**Comment by thejeshgn** [comment]
@devdattaT I think it would be great as a separate repo?

I have created a repo [landuse_maps](https://github.com/datameet/landuse_maps) if you like to use. Though I would leave it to you as you maintain this repo.

@sandeepgadhwal Thanks for the patience. Wait a for couple of days to resolve this. This data is useful. Will end up in one of datameet repos.

**Comment by sandeepgadhwal** [comment]
Closing to open another pull request

**Pull request closed without merging**
