### PR TITLE
Jaipur Municipal Data

### PR DESCRIPTION
**Pull request by sandeepgadhwal**
Added Layers of Jaipur Municipal Data

### CODE REVIEW

**Comment by devdattaT** [comment]
@sandeepgadhwal  Can you add the Readme for the three cities? Also there is no need for the Shapefiles;

**Comment by sandeepgadhwal** [comment]
@devdattaT I have added readme for all of them

**Comment by devdattaT** [comment]
Thank you so much @sandeepgadhwal

**Comment by thevikas** [comment]
Delhi municipal data is not separated for the three municipal corporations (east, south and north), each having its own ward number seq.

**Pull request merged**
